// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgrSNwfra3Mu8sCzKU-xJ5R1cuDIEVi2c',
    appId: '1:116558678544:web:a7fdafdad06296418b9895',
    messagingSenderId: '116558678544',
    projectId: 'flutter-social-app-cbfbf',
    authDomain: 'flutter-social-app-cbfbf.firebaseapp.com',
    storageBucket: 'flutter-social-app-cbfbf.firebasestorage.app',
    measurementId: 'G-YB26TL4LZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu-sWtnlTj0QCPKZCkMhdlweSwN7ji_Sk',
    appId: '1:116558678544:android:639f1aee3e36499d8b9895',
    messagingSenderId: '116558678544',
    projectId: 'flutter-social-app-cbfbf',
    storageBucket: 'flutter-social-app-cbfbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZXuaBY9LZ3wJCscaiC8s6LJF8mrkIew',
    appId: '1:116558678544:ios:7b3309e0f7c0cb638b9895',
    messagingSenderId: '116558678544',
    projectId: 'flutter-social-app-cbfbf',
    storageBucket: 'flutter-social-app-cbfbf.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZXuaBY9LZ3wJCscaiC8s6LJF8mrkIew',
    appId: '1:116558678544:ios:7b3309e0f7c0cb638b9895',
    messagingSenderId: '116558678544',
    projectId: 'flutter-social-app-cbfbf',
    storageBucket: 'flutter-social-app-cbfbf.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgrSNwfra3Mu8sCzKU-xJ5R1cuDIEVi2c',
    appId: '1:116558678544:web:5b9d8ae570e7d23b8b9895',
    messagingSenderId: '116558678544',
    projectId: 'flutter-social-app-cbfbf',
    authDomain: 'flutter-social-app-cbfbf.firebaseapp.com',
    storageBucket: 'flutter-social-app-cbfbf.firebasestorage.app',
    measurementId: 'G-8M19K2GXEY',
  );
}
